### ISSUE TITLE
Atom in molecule do not properly change charge values from set functions.

### ISSUE THREAD

**Issue by Mateus-RB** [Mateus-RB/MoleKing#41]
Atom in molecule do not properly change charge values from set functions. It is needed to adjust the code. The following python code resolve the problem.
`def setCharges(mol, log):

    mol2 = Molecule()

    for i in range(len(log)):

        if 'ESP charges:' in log[i]:

            start = i+2

        if 'Sum of ESP charges =' in log[i]:

            end = i

    s = 0

    for i in range(start, end):

        mol2.addAtom(mol[s].getAtomicSymbol(), mol[s].getX(), mol[s].getY(), mol[s].getZ(), float(log[i].split()[2]))

        s+=1

    return mol2
`

**Comment by phfmatias** [comment]
Basically, we were adding atom without any reference, E.g were modifying copys instead of instancies. 

Changes made: Added a reference to atomobj in `Molecule::getAtomObj()` function.

*Molecule.cpp*

`Atom& Molecule::getAtomObj(int number){
    return this->molecule[number];
}`

*Molecule.hpp*

`Atom& getAtomObj(int number);`


*Main.cpp*
`.def("__getitem__", &Molecule::getAtomObj, py::return_value_policy::reference)`

Also, we change some test that was not working properly.

` assert len(Ob['Occupied']) == 13
assert len(Ob['Unoccupied']) == 56`
